Algoritmo "Impar e Par 1"

Var
// Seção de comandos, procedimentos, funções, operadores, etc...
//n:numero inteiro
n:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etec...
escreval ("Digite um numero inteiro: ")
escreval (" ")
leia(n)
se (n mod 2=0) entao
escreval(" ")
escreva ("o numero", n, " é par")
senao
escreva (" ")
escreva ("o numero", n, " é impar")
FIMSE

FIMALGORITMO
