Algoritmo "Turnos"

Var
turno: caracter

Inicio
escreval ("Digite o turno que você estuda")
escreval (" M para Matutino")
escreval (" V para Vespertino")
escreval (" N para Noturno")
 leia (turno)
 se turno ="m" entao
 escreval ("Bom dia")
 senao
 se turno ="v" entao
 escreval ("Boa tarde")
 senao
 se turno ="n" entao
 escreval ("Boa noite")
 senao
 escreval ("Valor invalido")
 fimse
 fimse
 fimse
Fimalgoritmo